name: spanet

channels:
  - pytorch-nightly
  - nvidia/label/cuda-12.1.0
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10.*
  - conda
  - pip
  - cuda-toolkit
  - onnx

  - numpy=1.24
  - sympy
  - scikit-learn
  - numba
  - opt_einsum
  - h5py
  - cytoolz

  - pytorch=2.1
  - pytorch-lightning=2.0.7
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio

  - tensorboard
  - tensorboardx

  - jupyterlab
  - seaborn
  - rich
